language: cpp

compiler:
    - gcc
#    - clang
    
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_devtools
  - ./travis-tool.sh install_deps
#  - ./travis-tool.sh install_r testthat BH RcppEigen gnm ffbase ff gglot2
  
before_script:
  - sudo apt-get install libboost-dev  
  
script:
#    - mkdir -p standalone/build && (cd standalone/build && cmake .. && make)
    - ./travis-tool.sh run_tests
    - ls -l libs
    
after_failure:
    - ./travis-tool.sh dump_logs
    
notifications:
  recipients:
    - msuchard@gmail.com
  email:
    on_success: change
    on_failure: always
