#language: cpp
#compiler:
#- gcc
#sudo: required
#before_install:
#- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#- chmod 755 ./travis-tool.sh
#- ./travis-tool.sh bootstrap
#- sudo sed 's/-g//g' /etc/R/Makeconf > tmp
#- sudo mv tmp /etc/R/Makeconf
#- ./travis-tool.sh install_devtools
#- ./travis-tool.sh install_deps
#- ./travis-tool.sh install_r ggplot2 ff ffbase
#- ./travis-tool.sh install_github jimhester/covr
#- ./travis-tool.sh install_github eddelbuettel/drat
#before_script:
#- sudo apt-get install libboost-dev
#- export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
#- export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
#script:
#- ./travis-tool.sh run_tests
#- ls -l Cyclops.Rcheck/Cyclops/libs
#after_failure:
#- ./travis-tool.sh dump_logs
#notifications:
#  recipients:
#  - msuchard@gmail.com
#  email:
#    on_success: change
#    on_failure: always
#after_success:
#- Rscript -e 'library(covr);codecov()'
#- curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/development/trigger/e51f720d-c4e7-45df-b042-5d8a362bd7e0/
#- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
#  deploy.sh
#  - grep '\-g'  /etc/R/Makeconf | sed 's/-g//g' > ~/.R/Makevars # Turn off debug symbols

languague: c
sudo: required
dist: trusty

matrix:
  include:
    # gcc default
    - compiler: gcc
      addons:
        apt:
          update: true
          sources:
          - r-packages-precise
          packages:
          - r-base-dev
          - r-recommended
          - texinfo
          - qpdf
    # gcc 6
    - compiler: gcc
      addons:
        apt:
          update: true
          sources:
          - r-packages-precise
          - ubuntu-toolchain-r-test
          packages:
          - r-base-dev
          - r-recommended
          - texinfo
          - qpdf
          - g++-6
      before_script:
        - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
        - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
        - echo 'CC=gcc-6' > ~/.R/Makevars
        - echo 'CXX=g++-6' >> ~/.R/Makevars
        - echo 'CXX1X=g++-6' >> ~/.R/Makevars
        - echo 'PKG_CXXFLAGS= -std=c++14 -s -g1 -Wno-ignored-attributes -Wno-deprecated-declarations' >> ~/.R/Makevars

#addons:
#  apt:
#    sources:
#    - r-packages-precise
#    packages:
#    - r-base-dev
#    - r-recommended
#    - texinfo
#    - qpdf

cache:
  directories:
    - ~/Rlib     # R libraries
    - ~/texlive  # LaTex
    - ~/bin      # pandoc

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add Eddelbuttel launchpad repo
  - sudo add-apt-repository -y ppa:edd/misc
#  - ./run.sh bootstrap
#  - rm -rf ~/Rlib # Reinstall all packages
  - |
    if [[ "linux" == "linux" ]]; then
      mkdir -p ${OPENCL_ROOT}
      bash .travis/amd_sdk.sh ${AMDAPPSDK_VERSION}
      tar -xjf AMD-SDK.tar.bz2
      export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors
      mkdir -p ${OPENCL_VENDOR_PATH}
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT}
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd
      export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH}
      export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64;
      chmod +x ${AMDAPPSDKROOT}/bin/x86_64/clinfo
      ${AMDAPPSDKROOT}/bin/x86_64/clinfo
      rm AMD-APP-SDK*.sh
      rm AMD-SDK.tar.bz2
    fi

# install dependencies
install:
  # Save R packages in Rlib
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - mkdir -p ~/.R
  #
  - ./run.sh install_aptget r-cran-rcpp r-cran-bit r-cran-ff r-cran-ffbase r-cran-rcppparallel r-cran-rcppeigen r-cran-ggplot2 r-cran-testthat r-cran-gnm r-cran-devtools
  - ./run.sh install_r drat covr microbenchmark
  # Build LaTex and pandoc
#  - mkdir -p ~/bin
#  - wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-texlive | bash
#  - wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash
#  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  # Install R packages
  - Rscript -e "if (require('devtools')) install.packages('devtools')"
  - Rscript -e "if (require('covr')) devtools::install_github('jimhester/covr')"
  - Rscript -e "if (require('rmarkdown')) install.packages('rmarkdown')"
  - Rscript -e "if (require('knitr')) install.packages('knitr')"
  - Rscript -e "if (require('drat')) install.packages('drat')"
  - Rscript -e "if (require('ff')) install.packages('ff')"
  - Rscript -e "if (require('ffbase')) install.packages('ffbase')"
  - Rscript -e "if (require('ggplot2')) install.packages('ggplot2')"
  - Rscript -e "if (require('RcppParallel')) install.packages('RcppParallel')"
  - Rscript -e "if (require('BH')) install.packages('BH')"
  - Rscript -e "if (require('RcppEigen')) install.packages('RcppEigen')"
  - Rscript -e "if (require('testthat')) install.packages('testthat')"
  - Rscript -e "if (require('gnm')) install.packages('gnm')"
  - export CPLUS_INCLUDE_PATH=${AMDAPPSDKROOT}/include
  - export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH}
  - export LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LIBRARY_PATH}
  - Rscript -e "if (require('BoostCompiledLibraries')) { devtools::install_github('OHDSI/BoostCompiledLibraries') }"
  - Rscript -e "if (require('RcppBoostCompute')) { devtools::install_github('OHDSI/RcppBoostCompute') }"

before_script:
  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')

 # Build and check package
script:
  - R CMD build .
  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_TARBALL}" --as-cran
  - cat ${PKG_NAME}.Rcheck/00install.out # Print out install / compile log

after_success:
  - Rscript -e 'covr::codecov()'
  # Rebuild docker container
  - curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/broadsea-methodslibrary/trigger/f0b51cec-4027-4781-9383-4b38b42dd4f5/
  # Rebuild drat repo
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

env:
  global:
  - secure: OqWkvryQHJ8TCDu++1fjNNfd+ECuPH+og++cXgfpQ3QcTjReD0cc3dGP+tD3GX18H9jJa+MQzNXyBCHn8+o1b1MRiUGAKuxD0vsZ2iQ/1nZYiL2cKJbei36vJPVg82D68zOsE/G5rESKFOQKUC+OqNHcneyk1+cwsU7zvQTtBhU=
  - OPENCL_ROOT=$HOME/opencl
  - OPENCL_LIB=amdappsdk
  - OPENCL_VERSION="12"
  - AMDAPPSDK_VERSION=291 # OpenCL 1.2
  - AMDAPPSDKROOT=${OPENCL_ROOT}/AMDAPPSDK
