language: cpp
compiler:
    - gcc
    - clang
before_install:
script:
    - g++ -E -dM -std=c++98 -x c++ /dev/null > std1 && g++ -E -dM -std=c++0x -x c++ /dev/null > std2 && diff -u std1 std2 | grep '[+|-]^*#define' && rm std1 std2
    - mkdir -p standalone/build && (cd standalone/build && cmake .. && make)
notifications:
  recipients:
    - msuchard@gmail.com
  email:
    on_success: change
    on_failure: always 
    