# .travis.yml using container-based infrastructure
# from: https://github.com/jtilly/R-travis-container-example/blob/master/.travis.yml

language: c

# use containers
sudo: false

# install R: use r-packages-precise (https://cran.r-project.org/bin/linux/ubuntu/precise/)
# as source which is white listed (https://github.com/travis-ci/apt-source-whitelist/)
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - pandoc

# cache local R libraries directory:
cache:
  directories:
    - ~/Rlib

# before_install:
#  - sudo sed 's/-g//g' /etc/R/Makeconf > tmp # Turn off debug symbols
#  - sudo mv tmp /etc/R/Makeconf

# install the package and dependencies:
# - create directory for R libraries (if not already exists)
# - create .Renviron with location of R libraries
# - define R repository in .Rprofile
# - add .travis.yml to .Rbuildignore
# - install devtools if not already installed
# - install covr if not already installed
# - update all installed packages
# - install package with dependencies
install:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - mkdir -p ~/.R
#  - sed 's/-g//g' /etc/R/Makeconf > tmp # Turn off debug symbols
#  - cp tmp ~/.R/Makevars
#  - find / -name "Makeconf"
  - grep '\-g'  /etc/R/Makeconf | sed 's/-g//g' > ~/.R/Makevars # Turn off debug symbols
  - cat ~/.R/Makevars
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
  - Rscript -e 'if(!"ggplot2" %in% rownames(installed.packages())) { install.packages("ggplot2", dependencies = TRUE) }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'

# Build and check package
script:
  - R CMD build . --no-build-vignettes --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - PKG_NAME=$(ls -1t *.tar.gz | head -n 1 | sed 's/_.*gz//')
  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
  - ls -l ${PKG_NAME}.Rcheck/${PKG_NAME}/libs # Print out size of library
  - cat ${PKG_NAME}.Rcheck/00install.out # Print out install / compile log

# report coverage rate to coveralls
after_success:
#  - Rscript -e 'covr::coveralls(exclusions = "src/RcppExports.cpp")'
  # Rebuild docker container
  - curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/development/trigger/e51f720d-c4e7-45df-b042-5d8a362bd7e0/

# send e-mails if stuff changes
notifications:
  recipients:
    - msuchard@gmail.com
  email:
    on_success: change
    on_failure: always
