# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add our launchpad repo which has (inter alia) r-cran-rcmdcheck
  - sudo add-apt-repository -y ppa:edd/misc
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-rcpp r-cran-bit r-cran-ff r-cran-ffbase r-cran-rcppparallel

script:
  - ./run.sh run_tests

after_success:
  - Rscript -e 'covr::codecov()'
  # Rebuild docker container
  - curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/broadsea-methodslibrary/trigger/f0b51cec-4027-4781-9383-4b38b42dd4f5/
  # Rebuild drat repo
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change




#language: r
#sudo: required
#cache: packages
#r_packages:
#  - covr
#  - drat
#
#matrix:
#    include:
#    - os: linux
#      compiler: gcc
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['g++-5']
#      env:
#        - COMPILER=g++-5
#        - CC=gcc-5
#        - CXX=g++-5
#        - FORTRAN=gfortran-5
#
##matrix:
##  include:
##    # gcc default
##    - compiler: gcc
##    # gcc 6
##    - compiler: gcc
##      addons:
##        apt:
##          sources:
##          - ubuntu-toolchain-r-test
##          packages:
##          - g++-6
##      before_script:
##        - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
##        - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
##        - export CC=gcc-6
##        - export CXX=g++-6
##        - mkdir -p ~/.R
##        - echo 'CC=gcc-6' > ~/.R/Makevars
##        - echo 'CXX=g++-6' >> ~/.R/Makevars
##        - echo 'CXX1X=g++-6' >> ~/.R/Makevars
##        - echo 'PKG_CXXFLAGS= -std=c++14 -s -g1 -Wno-ignored-attributes -Wno-deprecated-declarations' >> ~/.R/Makevars
##
#
#before_install:
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
#  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 100
#  - mkdir -p ~/.R
#  - echo "VkVSPS01CkNDPWdjYyQoVkVSKSAtc3RkPWMxMSAKQ1hYPWcrKyQoVkVSKQpTSExJQl9DWFhMRD1nKyskKFZFUikKRkM9Z2ZvcnRyYW4KRjc3PWdmb3J0cmFuCg==" | base64 -d > ~/.R/Makevars
#  - cat ~/.R/Makevars
#
#before_script:
#  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
#  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
#
# # Build and check package
#script:
#  - R CMD build .
#  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_TARBALL}" --as-cran
#  - cat ${PKG_NAME}.Rcheck/00install.out # Print out install / compile log

after_success:
  - Rscript -e 'covr::codecov()'
  # Rebuild docker container
  - curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/broadsea-methodslibrary/trigger/f0b51cec-4027-4781-9383-4b38b42dd4f5/
  # Rebuild drat repo
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
