language: cpp
compiler:
    - gcc
    - clang
before_install:
script:
    - mkdir -p C/build && (cd C/build && cmake .. && make)
notifications:
  recipients:
    - msuchard@gmail.com
  email:
    on_success: change
    on_failure: always 
    